USE DATABASE INSURANCE_DB;
-- RAW staging tables
CREATE OR REPLACE TABLE RAW.CUSTOMERS_RAW (
  CUSTOMER_ID STRING,
  AGE NUMBER,
  GENDER STRING,
  CITY STRING,
  PLAN_TYPE STRING
);
CREATE OR REPLACE TABLE RAW.HOSPITALS_RAW (
  HOSPITAL_ID STRING,
  HOSPITAL_NAME STRING,
  HOSPITAL_CITY STRING,
  BASE_RATING FLOAT
);
CREATE OR REPLACE TABLE RAW.CLAIMS_RAW (
  CLAIM_ID STRING,
  CUSTOMER_ID STRING,
  CLAIM_AMOUNT FLOAT,
  CLAIM_TYPE STRING,
  CLAIM_DATE DATE,
  STATUS STRING,
  HOSPITAL_ID STRING
);
-- DEV/TEST transformed tables
CREATE OR REPLACE TABLE ${TARGET_SCHEMA}.CUSTOMERS_TRANSFORMED (
  CUSTOMER_ID STRING,
  AGE NUMBER,
  GENDER STRING,
  CITY STRING,
  PLAN_TYPE STRING
);
CREATE OR REPLACE TABLE ${TARGET_SCHEMA}.HOSPITALS_TRANSFORMED (
  HOSPITAL_ID STRING,
  HOSPITAL_NAME STRING,
  HOSPITAL_CITY STRING,
  BASE_RATING FLOAT
);
CREATE OR REPLACE TABLE ${TARGET_SCHEMA}.CLAIMS_TRANSFORMED (
  CLAIM_ID STRING,
  CUSTOMER_ID STRING,
  CLAIM_AMOUNT FLOAT,
  CLAIM_TYPE STRING,
  CLAIM_DATE DATE,
  STATUS STRING,
  HOSPITAL_ID STRING
);
-- PRESENTATION curated tables (fixed)
CREATE TABLE IF NOT EXISTS PRESENTATION.CUSTOMERS (
  CUSTOMER_ID STRING PRIMARY KEY,
  AGE NUMBER,
  GENDER STRING,
  CITY STRING,
  PLAN_TYPE STRING
);
CREATE TABLE IF NOT EXISTS PRESENTATION.HOSPITALS (
  HOSPITAL_ID STRING PRIMARY KEY,
  HOSPITAL_NAME STRING,
  HOSPITAL_CITY STRING,
  BASE_RATING FLOAT
);
CREATE TABLE IF NOT EXISTS PRESENTATION.CLAIMS (
  CLAIM_ID STRING PRIMARY KEY,
  CUSTOMER_ID STRING,
  CLAIM_AMOUNT FLOAT,
  CLAIM_TYPE STRING,
  CLAIM_DATE DATE,
  STATUS STRING,
  HOSPITAL_ID STRING
);