USE DATABASE INSURANCE_DB;
USE SCHEMA RAW;
CREATE OR REPLACE FILE FORMAT RAW.CSV_FF
  TYPE = CSV
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('', 'NULL')
  DATE_FORMAT = 'MM/DD/YYYY';
-- Clear RAW tables before loading
TRUNCATE TABLE RAW.CUSTOMERS_RAW;
TRUNCATE TABLE RAW.HOSPITALS_RAW;
TRUNCATE TABLE RAW.CLAIMS_RAW;
-- Load customers.csv
COPY INTO RAW.CUSTOMERS_RAW
FROM @INSURANCE_RAW_S3/customers/
FILE_FORMAT = RAW.CSV_FF
ON_ERROR = 'CONTINUE'
FORCE = TRUE;
-- Load hospitals.csv
COPY INTO RAW.HOSPITALS_RAW
FROM @INSURANCE_RAW_S3/hospitals/
FILE_FORMAT = RAW.CSV_FF
ON_ERROR = 'CONTINUE'
FORCE = TRUE;
-- Load multiple claims_*.csv files
COPY INTO RAW.CLAIMS_RAW
FROM @INSURANCE_RAW_S3/claims/
FILE_FORMAT = RAW.CSV_FF
ON_ERROR = 'CONTINUE'
FORCE = TRUE
PATTERN = '.*claims_.*\\.csv';
-- Optional sanity counts
SELECT 'CUSTOMERS_RAW' AS table_name, COUNT(*) AS row_count FROM RAW.CUSTOMERS_RAW
UNION ALL
SELECT 'HOSPITALS_RAW', COUNT(*) FROM RAW.HOSPITALS_RAW
UNION ALL
SELECT 'CLAIMS_RAW', COUNT(*) FROM RAW.CLAIMS_RAW;