USE DATABASE INSURANCE_DB;
USE SCHEMA ${TARGET_SCHEMA};
-- Overwrite transformed tables from RAW sources
CREATE OR REPLACE TABLE ${TARGET_SCHEMA}.CUSTOMERS_TRANSFORMED AS
SELECT DISTINCT
  CUSTOMER_ID, AGE, GENDER, CITY, PLAN_TYPE
FROM RAW.CUSTOMERS_RAW
WHERE CUSTOMER_ID IS NOT NULL;
--
CREATE OR REPLACE TABLE ${TARGET_SCHEMA}.HOSPITALS_TRANSFORMED AS
SELECT DISTINCT
  HOSPITAL_ID, HOSPITAL_NAME, CITY, RATING
FROM RAW.HOSPITALS_RAW
WHERE HOSPITAL_ID IS NOT NULL;
--
CREATE OR REPLACE TABLE ${TARGET_SCHEMA}.CLAIMS_TRANSFORMED AS
SELECT DISTINCT
  CLAIM_ID,
  CUSTOMER_ID,
  CLAIM_AMOUNT,
  CLAIM_TYPE,
  CLAIM_DATE,
  STATUS,
  HOSPITAL_ID
FROM RAW.CLAIMS_RAW
WHERE CLAIM_ID IS NOT NULL;
-- Optional: quick counts
SELECT 'CUSTOMERS_TRANSFORMED' AS table_name, COUNT(*) AS row_count FROM ${TARGET_SCHEMA}.CUSTOMERS_TRANSFORMED
UNION ALL
SELECT 'HOSPITALS_TRANSFORMED', COUNT(*) FROM ${TARGET_SCHEMA}.HOSPITALS_TRANSFORMED
UNION ALL
SELECT 'CLAIMS_TRANSFORMED', COUNT(*) FROM ${TARGET_SCHEMA}.CLAIMS_TRANSFORMED;