USE DATABASE INSURANCE_DB;

-- Merge customers
MERGE INTO PRESENTATION.CUSTOMERS AS tgt
USING (
  SELECT DISTINCT CUSTOMER_ID, AGE, GENDER, CITY, PLAN_TYPE
  FROM DEV.CUSTOMERS_TRANSFORMED
) AS src
ON tgt.CUSTOMER_ID = src.CUSTOMER_ID
WHEN MATCHED THEN UPDATE SET
  AGE = src.AGE,
  GENDER = src.GENDER,
  CITY = src.CITY,
  PLAN_TYPE = src.PLAN_TYPE
WHEN NOT MATCHED THEN INSERT (CUSTOMER_ID, AGE, GENDER, CITY, PLAN_TYPE)
VALUES (src.CUSTOMER_ID, src.AGE, src.GENDER, src.CITY, src.PLAN_TYPE);

-- Merge hospitals
MERGE INTO PRESENTATION.HOSPITALS AS tgt
USING (
  SELECT DISTINCT HOSPITAL_ID, HOSPITAL_NAME, CITY, RATING
  FROM DEV.HOSPITALS_TRANSFORMED
) AS src
ON tgt.HOSPITAL_ID = src.HOSPITAL_ID
WHEN MATCHED THEN UPDATE SET
  HOSPITAL_NAME = src.HOSPITAL_NAME,
  CITY = src.CITY,
  RATING = src.RATING
WHEN NOT MATCHED THEN INSERT (HOSPITAL_ID, HOSPITAL_NAME, CITY, RATING)
VALUES (src.HOSPITAL_ID, src.HOSPITAL_NAME, src.CITY, src.RATING);

-- Merge claims
MERGE INTO PRESENTATION.CLAIMS AS tgt
USING (
  SELECT DISTINCT
    CLAIM_ID, CUSTOMER_ID, CLAIM_AMOUNT, CLAIM_TYPE, CLAIM_DATE, STATUS, HOSPITAL_ID
  FROM DEV.CLAIMS_TRANSFORMED
) AS src
ON tgt.CLAIM_ID = src.CLAIM_ID
WHEN MATCHED THEN UPDATE SET
  CUSTOMER_ID = src.CUSTOMER_ID,
  CLAIM_AMOUNT = src.CLAIM_AMOUNT,
  CLAIM_TYPE = src.CLAIM_TYPE,
  CLAIM_DATE = src.CLAIM_DATE,
  STATUS = src.STATUS,
  HOSPITAL_ID = src.HOSPITAL_ID
WHEN NOT MATCHED THEN INSERT (
  CLAIM_ID, CUSTOMER_ID, CLAIM_AMOUNT, CLAIM_TYPE, CLAIM_DATE, STATUS, HOSPITAL_ID
) VALUES (
  src.CLAIM_ID, src.CUSTOMER_ID, src.CLAIM_AMOUNT, src.CLAIM_TYPE, src.CLAIM_DATE, src.STATUS, src.HOSPITAL_ID
);
