USE DATABASE INSURANCE_DB;
-- Row counts
SELECT 'DEV.CUSTOMERS_TRANSFORMED' AS table_name, COUNT(*) AS row_count FROM DEV.CUSTOMERS_TRANSFORMED
UNION ALL
SELECT 'DEV.HOSPITALS_TRANSFORMED', COUNT(*) FROM DEV.HOSPITALS_TRANSFORMED
UNION ALL
SELECT 'DEV.CLAIMS_TRANSFORMED', COUNT(*) FROM DEV.CLAIMS_TRANSFORMED
UNION ALL
SELECT 'PRESENTATION.CUSTOMERS', COUNT(*) FROM PRESENTATION.CUSTOMERS
UNION ALL
SELECT 'PRESENTATION.HOSPITALS', COUNT(*) FROM PRESENTATION.HOSPITALS
UNION ALL
SELECT 'PRESENTATION.CLAIMS', COUNT(*) FROM PRESENTATION.CLAIMS;
-- Null checks in curated
SELECT COUNT(*) AS null_customer_ids FROM PRESENTATION.CUSTOMERS WHERE CUSTOMER_ID IS NULL;
SELECT COUNT(*) AS null_hospital_ids FROM PRESENTATION.HOSPITALS WHERE HOSPITAL_ID IS NULL;
SELECT COUNT(*) AS null_claim_ids FROM PRESENTATION.CLAIMS WHERE CLAIM_ID IS NULL;
-- Referential integrity
SELECT COUNT(*) AS bad_customer_refs
FROM PRESENTATION.CLAIMS c
LEFT JOIN PRESENTATION.CUSTOMERS cu ON c.CUSTOMER_ID = cu.CUSTOMER_ID
WHERE cu.CUSTOMER_ID IS NULL;
--
SELECT COUNT(*) AS bad_hospital_refs
FROM PRESENTATION.CLAIMS c
LEFT JOIN PRESENTATION.HOSPITALS h ON c.HOSPITAL_ID = h.HOSPITAL_ID
WHERE h.HOSPITAL_ID IS NULL;
-- Domain checks
SELECT COUNT(*) AS negative_claim_amounts FROM PRESENTATION.CLAIMS WHERE CLAIM_AMOUNT < 0;
SELECT COUNT(*) AS invalid_hospital_ratings FROM PRESENTATION.HOSPITALS WHERE BASE_RATING < 0 OR BASE_RATING > 5;
-- Status domain
SELECT DISTINCT STATUS FROM PRESENTATION.CLAIMS WHERE STATUS NOT IN ('Approved', 'Pending', 'Rejected');